n = input('Type something: ')
print(type(n))
print('Is it a word? ', n.isalpha())
print('Is it a number? ', n.isnumeric())
print('Is it alphanumeric? ', n.isalnum())
print('Is it an identifier? ', n.isidentifier())
print('Is it a space? ', n.isspace())
print('Is it printable? ', n.isprintable())
print('Is it in Uppercase? ', n.isupper())
print('Is it in lowercase? ', n.islower())
